name: flutter_ume_kit_designer_check
description: UI check tool for designer.
version: 1.0.0
homepage: https://github.com/cfug/flutter_ume_kit

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume: ^1.1.2
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
